### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by JocelynTse** [JocelynTse/project-1-group-5#3]
Review of our proposal for Project 1 is requested.
Please see project proposal in readme.md.

**Comment by iAmWillShepherd** [comment]
You will need to create a PR for this so that I can make comments inline if needed. Here are the [docs](https://help.github.com/articles/creating-a-pull-request/) for accomplishing this and some [blog](https://yangsu.github.io/pull-request-tutorial/) I found doing a Google search.

**Comment by georgejacobt** [comment]
Hi Will, Created a PR..please let know if there is anything more we need to do..
